# Generated by Django 3.2 on 2021-04-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210415_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclubuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='User Email Address'),
        ),
    ]
